### ISSUE TITLE
Re-configuring a V9 simulation in V10 and export to PKML -> Error

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/MoBi#573]
This has something to do with the new protein expression logic, I will send you the simulation via email.

Simulation was created with V9. Opening the simulation in V10, re-configuring, then

- Run simulation: 

```
Formula id=35012: object with id=35011 not found

For more information or questions, please visit the Open Systems Pharmacology Forum (http://forum.open-systems-pharmacology.org).
```

Export simulation to pkml and try to load:

```
Unable to resolve path 'Start amount' for entity 'DPP4' with path 'GHM|Organism|Liver|Pericentral|Plasma|DPP4'

For more information or questions, please visit the Open Systems Pharmacology Forum (http://forum.open-systems-pharmacology.org).
```

also cannot load in R.

**Comment by msevestre** [comment]
Was the simulation created in PKSim and exported to pkml and it is there corrupt? Or did you create the simulation in PKSimn, exporter to pkml and then created new one using the building blocks?

**Comment by PavelBal** [comment]
The simulation was created in PK-Sim V9 and then further developed in MoBi. The pkml was exported from MoBi (the one that I shared was saved from V9 MoBi).

If this simulation is loaded in V10 (or the whole project is opened with V10), and then a simulation is created and exported - it cannot be loaded (or simulated).

**Comment by PavelBal** [comment]
Check which formulas have to be changed (check for Volume > 0).

**Comment by msevestre** [comment]
Not closing yet until @PavelBal confirms it is fixed

**Comment by msevestre** [comment]
@PavelBal Can you confirm that this is fixed? Or are we missing other formula to be converted automatically?

**Comment by PavelBal** [comment]
I tried this out and it works.

However, if a similar case occurs (NaN parameter removed)) e.g. while the user defined an equation that evaluates to NaN, the error is still "Object ID blabla not found in formula ID...". Is there a chance to make this message more informative? E.g., the error in R says "cannot load simulation because parameter xxx is not found".

**Comment by msevestre** [comment]
yeah even pksim shows it on load
PK-Sim®

Could not load simulation from file 'C:\tests\10.0\573\S2.pkml'.
-----------------------------------------------------
Unable to resolve path '..|..|Glucose|Total_Glucose_Concentration' for entity 'Glucose_Hexokinase_metabolizationRate' with path 'S2|Organism|Liver|Pericentral|BloodCells|Glucose-Hexokinase-Default|Glucose_Hexokinase_metabolizationRate'

For more information or questions, please visit the Open Systems Pharmacology Forum (http://forum.open-systems-pharmacology.org).

**Comment by msevestre** [comment]
ok ok I think I know why
We check that everythign is all good

Then we remove parameters

and then we need to check again. This happens in core. Going to move
